name: ci-servicio-bdd

on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  build-and-deploy:
    uses: otsugua004/devops-pipelines/.github/workflows/docker-workflow.yml@main
    with:
      docker_image_name: servicio-bdd
    secrets: inherit